name = "aicollab-status-page"
main = "dist/main.js"
workers_dev = true
compatibility_date = "2021-07-23"
no_bundle = true

[[kv_namespaces]]
binding = "KV_STATUS_PAGE"
id = "6b969f291cd340538c19e09296db5f51"

[triggers]
crons = ["*/5 * * * *"]

[site]
bucket = "out"
